### PR TITLE
Add unit tests

### LINKED ISSUE #8: Add unit tests
**unit test refs:**
_it currently seems not possible to use jest with Electron vue, the recommended way is to use karma + mocha: https://simulatedgreg.gitbooks.io/electron-vue/content/en/unittesting.html_
* https://www.npmjs.com/package/karma
* https://www.npmjs.com/package/chai
* https://www.npmjs.com/package/karma-mocha
* https://www.npmjs.com/package/karma-chai
* https://www.npmjs.com/package/karma-webpack
* https://www.npmjs.com/package/karma-electron

### PR DESCRIPTION
**Pull request by fdaveine**
Fix #8

### CODE REVIEW

**Comment by fdaveine** [comment]
@antoinelibert to review

**Comment by antoinelibert** [comment]
I'm not sure I understand but there is no end to end tests yet, right? All I see are unittests which could have been tested using the method we used in ftl-app?

**Comment by fdaveine** [comment]
> I'm not sure I understand but there is no end to end tests yet, right? All I see are unittests which could have been tested using the method we used in ftl-app?

Yes only unittest for now (https://github.com/exotic-matter-sas/paper-matter-import-export/issues/8#issuecomment-627240604), not sure to understand "which could have been tested using the method we used in ftl-app".

**Comment by antoinelibert** [comment]
> not sure to understand "which could have been tested using the method we used in ftl-app".

I mean using Jest.

**Comment by fdaveine** [comment]
> > not sure to understand "which could have been tested using the method we used in ftl-app".
> 
> I mean using Jest.

electron-vue doesn't support jest as a test framework : see https://github.com/exotic-matter-sas/paper-matter-import-export/issues/8

**Pull request merged**
